@host = http://localhost
@port = 5207
@RestaurantsPractice.API_HostAddress = {{host}}:{{port}}

GET {{RestaurantsPractice.API_HostAddress}}/weatherforecast/example
Accept: application/json
ProjectUrl: {{$projectUrl}}
Guid:{{$guid}}
LocalDate: {{$datetime iso8601}}
Random-int: {{$randomInt}}

###

POST {{RestaurantsPractice.API_HostAddress}}/weatherforecast
Content-type: application/json
{
  "email":"nile.coderiver@gmail.com"
}