@host = http://localhost
@port = 5207
@RestaurantsPractice.API_HostAddress = https://localhost:7162

# GET {{RestaurantsPractice.API_HostAddress}}/weatherforecast/23/example?max=123
# Accept: application/json
# ProjectUrl: {{$projectUrl}}
# Guid:{{$guid}}
# LocalDate: {{$datetime iso8601}}
# Random-int: {{$randomInt}}

# ###

POST {{RestaurantsPractice.API_HostAddress}}/weatherforecast
Content-Type: application/json

"Nile Kim"

###

GET {{RestaurantsPractice.API_HostAddress}}/weatherforecast/currentDay

###

GET {{RestaurantsPractice.API_HostAddress}}/weatherforecast/example?resultNum=4&minTempC=5&maxTempC=35

###
